### ISSUE TITLE
docker部署之后无法访问音乐平台

### ISSUE THREAD

**Issue by mikutechnology** [xizeyoupan/Meting-API#11]
使用/test访问，页面无法加载，下面是运行日志

Trace: TypeError: error sending request for url (http://c.y.qq.com/qzone/fcg-bin/fcg_ucc_getcdinfo_byids_cp.fcg?type=1&utf8=1&disstid=7326220405&loginUin=0&format=json): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
    at async mainFetch (deno:ext/fetch/26_fetch.js:267:14)
    at async fetch (deno:ext/fetch/26_fetch.js:491:9)
    at async get_playlist (file:///app/dist/deno.js:2073:16)
    at async Object.handle (file:///app/dist/deno.js:2142:16)
    at async api_default (file:///app/dist/deno.js:2572:14)
    at async file:///app/dist/deno.js:3942:5
    at async file:///app/dist/deno.js:3986:7
    at async file:///app/dist/deno.js:3888:50
    at async Server.#respond (https://deno.land/std@0.187.0/http/server.ts:299:18)
    at Hono.errorHandler (file:///app/dist/deno.js:3754:15)
    at file:///app/dist/deno.js:2930:27
    at async file:///app/dist/deno.js:3942:5
    at async file:///app/dist/deno.js:3986:7
    at async file:///app/dist/deno.js:3888:50
    at async Server.#respond (https://deno.land/std@0.187.0/http/server.ts:299:18)
  --> GET /api 500 20s
Trace: TypeError: error sending request for url (https://yt-ra.2333332.xyz/api?server=ytmusic&type=song&id=G3s98l2-GXg): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
    at async mainFetch (deno:ext/fetch/26_fetch.js:267:14)
    at async fetch (deno:ext/fetch/26_fetch.js:491:9)
    at async Object.handle3 [as handle] (file:///app/dist/deno.js:2503:14)
    at async api_default (file:///app/dist/deno.js:2572:14)
    at async file:///app/dist/deno.js:3942:5
    at async file:///app/dist/deno.js:3986:7
    at async file:///app/dist/deno.js:3888:50
    at async Server.#respond (https://deno.land/std@0.187.0/http/server.ts:299:18)
    at Hono.errorHandler (file:///app/dist/deno.js:3754:15)
    at file:///app/dist/deno.js:2930:27
    at async file:///app/dist/deno.js:3942:5
    at async file:///app/dist/deno.js:3986:7
    at async file:///app/dist/deno.js:3888:50
    at async Server.#respond (https://deno.land/std@0.187.0/http/server.ts:299:18)
  --> GET /api 500 20s
Trace: TypeError: error sending request for url (http://u.y.qq.com/cgi-bin/musicu.fcg?data=%7B%22songinfo%22%3A%7B%22method%22%3A%22get_song_detail_yqq%22%2C%22module%22%3A%22music.pf_song_detail_svr%22%2C%22param%22%3A%7B%22song_mid%22%3A%22002Rnpvi058Qdm%22%7D%7D%7D): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
    at async mainFetch (deno:ext/fetch/26_fetch.js:267:14)
    at async fetch (deno:ext/fetch/26_fetch.js:491:9)
    at async get_song_info (file:///app/dist/deno.js:2042:16)
    at async Object.handle (file:///app/dist/deno.js:2139:16)
    at async api_default (file:///app/dist/deno.js:2572:14)
    at async file:///app/dist/deno.js:3942:5
    at async file:///app/dist/deno.js:3986:7
    at async file:///app/dist/deno.js:3888:50
    at async Server.#respond (https://deno.land/std@0.187.0/http/server.ts:299:18)
    at Hono.errorHandler (file:///app/dist/deno.js:3754:15)
    at file:///app/dist/deno.js:2930:27
    at async file:///app/dist/deno.js:3942:5
    at async file:///app/dist/deno.js:3986:7
    at async file:///app/dist/deno.js:3888:50
    at async Server.#respond (https://deno.land/std@0.187.0/http/server.ts:299:18)
  --> GET /api 500 20s
Trace: TypeError: error sending request for url (https://yt-ra.2333332.xyz/api?server=ytmusic&type=playlist&id=RDCLAK5uy_l12ynH8dyLsBmE11ToAHLm9P04NS2i9ME): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
    at async mainFetch (deno:ext/fetch/26_fetch.js:267:14)
    at async fetch (deno:ext/fetch/26_fetch.js:491:9)
    at async Object.handle3 [as handle] (file:///app/dist/deno.js:2503:14)
    at async api_default (file:///app/dist/deno.js:2572:14)
    at async file:///app/dist/deno.js:3942:5
    at async file:///app/dist/deno.js:3986:7
    at async file:///app/dist/deno.js:3888:50
    at async Server.#respond (https://deno.land/std@0.187.0/http/server.ts:299:18)
    at Hono.errorHandler (file:///app/dist/deno.js:3754:15)
    at file:///app/dist/deno.js:2930:27
    at async file:///app/dist/deno.js:3942:5
    at async file:///app/dist/deno.js:3986:7
    at async file:///app/dist/deno.js:3888:50
    at async Server.#respond (https://deno.land/std@0.187.0/http/server.ts:299:18)
  --> GET /api 500 20s
Trace: TypeError: error sending request for url (https://music.163.com/api/v6/playlist/detail): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
    at async mainFetch (deno:ext/fetch/26_fetch.js:267:14)
    at async fetch (deno:ext/fetch/26_fetch.js:491:9)
    at async request (file:///app/dist/deno.js:2353:11)
    at async get_playlist2 (file:///app/dist/deno.js:2383:13)
    at async Object.handle2 [as handle] (file:///app/dist/deno.js:2483:16)
    at async api_default (file:///app/dist/deno.js:2572:14)
    at async file:///app/dist/deno.js:3942:5
    at async file:///app/dist/deno.js:3986:7
    at async file:///app/dist/deno.js:3888:50
    at async Server.#respond (https://deno.land/std@0.187.0/http/server.ts:299:18)
    at Hono.errorHandler (file:///app/dist/deno.js:3754:15)
    at file:///app/dist/deno.js:2930:27
    at async file:///app/dist/deno.js:3942:5
    at async file:///app/dist/deno.js:3986:7
    at async file:///app/dist/deno.js:3888:50
    at async Server.#respond (https://deno.land/std@0.187.0/http/server.ts:299:18)
  --> GET /api 500 20s
Trace: TypeError: error sending request for url (https://music.163.com/weapi/v3/song/detail): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
    at async mainFetch (deno:ext/fetch/26_fetch.js:267:14)
    at async fetch (deno:ext/fetch/26_fetch.js:491:9)
    at async request (file:///app/dist/deno.js:2353:11)
    at async get_song_info2 (file:///app/dist/deno.js:2429:13)
    at async Object.handle2 [as handle] (file:///app/dist/deno.js:2480:16)
    at async api_default (file:///app/dist/deno.js:2572:14)
    at async file:///app/dist/deno.js:3942:5
    at async file:///app/dist/deno.js:3986:7
    at async file:///app/dist/deno.js:3888:50
    at async Server.#respond (https://deno.land/std@0.187.0/http/server.ts:299:18)
    at Hono.errorHandler (file:///app/dist/deno.js:3754:15)
    at file:///app/dist/deno.js:2930:27
    at async file:///app/dist/deno.js:3942:5
    at async file:///app/dist/deno.js:3986:7
    at async file:///app/dist/deno.js:3888:50
    at async Server.#respond (https://deno.land/std@0.187.0/http/server.ts:299:18)
  --> GET /api 500 20s
Trace: TypeError: error sending request for url (http://c.y.qq.com/qzone/fcg-bin/fcg_ucc_getcdinfo_byids_cp.fcg?type=1&utf8=1&disstid=7326220405&loginUin=0&format=json): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
    at async mainFetch (deno:ext/fetch/26_fetch.js:267:14)
    at async fetch (deno:ext/fetch/26_fetch.js:491:9)
    at async get_playlist (file:///app/dist/deno.js:2073:16)
    at async Object.handle (file:///app/dist/deno.js:2142:16)
    at async api_default (file:///app/dist/deno.js:2572:14)
    at async file:///app/dist/deno.js:3942:5
    at async file:///app/dist/deno.js:3986:7
    at async file:///app/dist/deno.js:3888:50
    at async Server.#respond (https://deno.land/std@0.187.0/http/server.ts:299:18)
    at Hono.errorHandler (file:///app/dist/deno.js:3754:15)
    at file:///app/dist/deno.js:2930:27
    at async file:///app/dist/deno.js:3942:5
    at async file:///app/dist/deno.js:3986:7
    at async file:///app/dist/deno.js:3888:50
    at async Server.#respond (https://deno.land/std@0.187.0/http/server.ts:299:18)
  --> GET /api 500 20s
Trace: TypeError: error sending request for url (https://yt-ra.2333332.xyz/api?server=ytmusic&type=song&id=G3s98l2-GXg): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
    at async mainFetch (deno:ext/fetch/26_fetch.js:267:14)
    at async fetch (deno:ext/fetch/26_fetch.js:491:9)
    at async Object.handle3 [as handle] (file:///app/dist/deno.js:2503:14)
    at async api_default (file:///app/dist/deno.js:2572:14)
    at async file:///app/dist/deno.js:3942:5
    at async file:///app/dist/deno.js:3986:7
    at async file:///app/dist/deno.js:3888:50
    at async Server.#respond (https://deno.land/std@0.187.0/http/server.ts:299:18)
    at Hono.errorHandler (file:///app/dist/deno.js:3754:15)
    at file:///app/dist/deno.js:2930:27
    at async file:///app/dist/deno.js:3942:5
    at async file:///app/dist/deno.js:3986:7
    at async file:///app/dist/deno.js:3888:50
    at async Server.#respond (https://deno.land/std@0.187.0/http/server.ts:299:18)
Trace: TypeError: error sending request for url (http://u.y.qq.com/cgi-bin/musicu.fcg?data=%7B%22songinfo%22%3A%7B%22method%22%3A%22get_song_detail_yqq%22%2C%22module%22%3A%22music.pf_song_detail_svr%22%2C%22param%22%3A%7B%22song_mid%22%3A%22002Rnpvi058Qdm%22%7D%7D%7D): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
    at async mainFetch (deno:ext/fetch/26_fetch.js:267:14)
    at async fetch (deno:ext/fetch/26_fetch.js:491:9)
    at async get_song_info (file:///app/dist/deno.js:2042:16)
    at async Object.handle (file:///app/dist/deno.js:2139:16)
    at async api_default (file:///app/dist/deno.js:2572:14)
    at async file:///app/dist/deno.js:3942:5
    at async file:///app/dist/deno.js:3986:7
    at async file:///app/dist/deno.js:3888:50
    at async Server.#respond (https://deno.land/std@0.187.0/http/server.ts:299:18)
    at Hono.errorHandler (file:///app/dist/deno.js:3754:15)
    at file:///app/dist/deno.js:2930:27
    at async file:///app/dist/deno.js:3942:5
    at async file:///app/dist/deno.js:3986:7
    at async file:///app/dist/deno.js:3888:50
    at async Server.#respond (https://deno.land/std@0.187.0/http/server.ts:299:18)
  --> GET /api 500 20s
  --> GET /api 500 20s
Trace: TypeError: error sending request for url (https://yt-ra.2333332.xyz/api?server=ytmusic&type=playlist&id=RDCLAK5uy_l12ynH8dyLsBmE11ToAHLm9P04NS2i9ME): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
    at async mainFetch (deno:ext/fetch/26_fetch.js:267:14)
    at async fetch (deno:ext/fetch/26_fetch.js:491:9)
    at async Object.handle3 [as handle] (file:///app/dist/deno.js:2503:14)
    at async api_default (file:///app/dist/deno.js:2572:14)
    at async file:///app/dist/deno.js:3942:5
    at async file:///app/dist/deno.js:3986:7
    at async file:///app/dist/deno.js:3888:50
    at async Server.#respond (https://deno.land/std@0.187.0/http/server.ts:299:18)
    at Hono.errorHandler (file:///app/dist/deno.js:3754:15)
    at file:///app/dist/deno.js:2930:27
    at async file:///app/dist/deno.js:3942:5
    at async file:///app/dist/deno.js:3986:7
    at async file:///app/dist/deno.js:3888:50
    at async Server.#respond (https://deno.land/std@0.187.0/http/server.ts:299:18)
  --> GET /api 500 20s
Trace: TypeError: error sending request for url (https://music.163.com/weapi/v3/song/detail): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
    at async mainFetch (deno:ext/fetch/26_fetch.js:267:14)
    at async fetch (deno:ext/fetch/26_fetch.js:491:9)
    at async request (file:///app/dist/deno.js:2353:11)
    at async get_song_info2 (file:///app/dist/deno.js:2429:13)
    at async Object.handle2 [as handle] (file:///app/dist/deno.js:2480:16)
    at async api_default (file:///app/dist/deno.js:2572:14)
    at async file:///app/dist/deno.js:3942:5
    at async file:///app/dist/deno.js:3986:7
    at async file:///app/dist/deno.js:3888:50
    at async Server.#respond (https://deno.land/std@0.187.0/http/server.ts:299:18)
    at Hono.errorHandler (file:///app/dist/deno.js:3754:15)
    at file:///app/dist/deno.js:2930:27
    at async file:///app/dist/deno.js:3942:5
    at async file:///app/dist/deno.js:3986:7
    at async file:///app/dist/deno.js:3888:50
    at async Server.#respond (https://deno.land/std@0.187.0/http/server.ts:299:18)
  --> GET /api 500 20s
Trace: TypeError: error sending request for url (https://music.163.com/api/v6/playlist/detail): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
    at async mainFetch (deno:ext/fetch/26_fetch.js:267:14)
    at async fetch (deno:ext/fetch/26_fetch.js:491:9)
    at async request (file:///app/dist/deno.js:2353:11)
    at async get_playlist2 (file:///app/dist/deno.js:2383:13)
    at async Object.handle2 [as handle] (file:///app/dist/deno.js:2483:16)
    at async api_default (file:///app/dist/deno.js:2572:14)
    at async file:///app/dist/deno.js:3942:5
    at async file:///app/dist/deno.js:3986:7
    at async file:///app/dist/deno.js:3888:50
    at async Server.#respond (https://deno.land/std@0.187.0/http/server.ts:299:18)
    at Hono.errorHandler (file:///app/dist/deno.js:3754:15)
    at file:///app/dist/deno.js:2930:27
    at async file:///app/dist/deno.js:3942:5
    at async file:///app/dist/deno.js:3986:7
    at async file:///app/dist/deno.js:3888:50
    at async Server.#respond (https://deno.land/std@0.187.0/http/server.ts:299:18)
  --> GET /api 500 20s

**Comment by xizeyoupan** [comment]
看起来是dns问题，先确认下你系统的网络状况？

**Comment by mikutechnology** [comment]
我这个是部署在腾讯的轻量云服务器上的，应该不存在dns的问题吧，我之前部署都没问题的

**Comment by xizeyoupan** [comment]
在我看来，DNS 解析已损坏。
您是否能够在运行 docker 容器的主机上解析主机名？
而且，如果可以的话，请尝试检查是否可以通过 docker 命令从容器中解析主机。

```
docker exec -it <container-name> getent hosts <hostname-to-resolve>
# Example
docker exec -it meting getent hosts c.y.qq.com
```

**Comment by mikutechnology** [comment]
我已经解决了，是我docker出问题了，我重新安装docker之后就可以正常使用了。抱歉
