### ISSUE TITLE
搭建好后，访问了3000端口产生了如下的 ERR_INVALID_THIS 错误是什么原因呢？

### ISSUE THREAD

**Issue by miuzkle** [xizeyoupan/Meting-API#21]
root@miuzkle-nas-debian:/home/miuzkle/project/hexo_blog/source/self/meting-api# npm i
npm run build:all
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

added 158 packages, and audited 159 packages in 18s

35 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (2 moderate, 3 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
npm notice 
npm notice New minor version of npm available! 10.2.4 -> 10.5.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.5.0
npm notice Run npm install -g npm@10.5.0 to update!
npm notice 

> meting-backend-js@1.0.6 build:all
> node esbuild.config.js 

root@miuzkle-nas-debian:/home/miuzkle/project/hexo_blog/source/self/meting-api# ls
Dockerfile  api     assets   dist               node.js       package-lock.json  scripts  test
README.md   app.js  deno.js  esbuild.config.js  node_modules  package.json       src      vercel.json
root@miuzkle-nas-debian:/home/miuzkle/project/hexo_blog/source/self/meting-api# node node.js
Trace: TypeError [ERR_INVALID_THIS]: Value of "this" must be of type URLSearchParams
    at Proxy.getAll (node:internal/url:527:13)
    at Proxy.<anonymous> (/home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/@remix-run/web-fetch/dist/lib.node.cjs:1034:44)
    at Proxy.get (/home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/@remix-run/web-fetch/dist/lib.node.cjs:1067:23)
    at HonoRequest.header (file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/request.js:50:31)
    at file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/middleware/cors/index.js:26:47
    at dispatch (file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/compose.js:24:17)
    at file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/compose.js:7:12
    at file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/hono-base.js:237:21
    at Hono.dispatch (file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/hono-base.js:248:7)
    at Hono.fetch (file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/hono-base.js:39:19) {
  code: 'ERR_INVALID_THIS'
}
    at errorHandler (file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/hono-base.js:19:11)
    at file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/compose.js:58:33
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/hono-base.js:238:62
    at async Server.<anonymous> (/home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/@hono/node-server/dist/server.js:48:20)
Trace: TypeError [ERR_INVALID_THIS]: Value of "this" must be of type URLSearchParams
    at Proxy.has (node:internal/url:546:13)
    at Proxy.<anonymous> (/home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/@remix-run/web-fetch/dist/lib.node.cjs:1034:44)
    at new Response (/home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/@remix-run/web-fetch/dist/lib.node.cjs:1227:33)
    at new NodeResponse (/home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/@hono/node-server/dist/fetch.js:24:1)
    at Context.newResponse (file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/context.js:106:14)
    at Context.text (file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/context.js:124:45)
    at errorHandler (file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/hono-base.js:21:12)
    at file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/compose.js:58:33
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/hono-base.js:238:62 {
  code: 'ERR_INVALID_THIS'
}
    at Hono.errorHandler (file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/hono-base.js:19:11)
    at Hono.handleError (file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/hono-base.js:185:19)
    at file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/hono-base.js:246:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server.<anonymous> (/home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/@hono/node-server/dist/server.js:48:20)
node:internal/url:527
      throw new ERR_INVALID_THIS('URLSearchParams');
            ^

TypeError [ERR_INVALID_THIS]: Value of "this" must be of type URLSearchParams
    at Proxy.getAll (node:internal/url:527:13)
    at Proxy.<anonymous> (/home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/@remix-run/web-fetch/dist/lib.node.cjs:1034:44)
    at Proxy.get (/home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/@remix-run/web-fetch/dist/lib.node.cjs:1067:23)
    at Server.<anonymous> (/home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/@hono/node-server/dist/server.js:53:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_THIS'
}

Node.js v20.11.1
root@miuzkle-nas-debian:/home/miuzkle/project/hexo_blog/source/self/meting-api# node node.js
Trace: TypeError [ERR_INVALID_THIS]: Value of "this" must be of type URLSearchParams
    at Proxy.getAll (node:internal/url:527:13)
    at Proxy.<anonymous> (/home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/@remix-run/web-fetch/dist/lib.node.cjs:1034:44)
    at Proxy.get (/home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/@remix-run/web-fetch/dist/lib.node.cjs:1067:23)
    at HonoRequest.header (file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/request.js:50:31)
    at file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/middleware/cors/index.js:26:47
    at dispatch (file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/compose.js:24:17)
    at file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/compose.js:7:12
    at file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/hono-base.js:237:21
    at Hono.dispatch (file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/hono-base.js:248:7)
    at Hono.fetch (file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/hono-base.js:39:19) {
  code: 'ERR_INVALID_THIS'
}
    at errorHandler (file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/hono-base.js:19:11)
    at file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/compose.js:58:33
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/hono-base.js:238:62
    at async Server.<anonymous> (/home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/@hono/node-server/dist/server.js:48:20)
Trace: TypeError [ERR_INVALID_THIS]: Value of "this" must be of type URLSearchParams
    at Proxy.has (node:internal/url:546:13)
    at Proxy.<anonymous> (/home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/@remix-run/web-fetch/dist/lib.node.cjs:1034:44)
    at new Response (/home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/@remix-run/web-fetch/dist/lib.node.cjs:1227:33)
    at new NodeResponse (/home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/@hono/node-server/dist/fetch.js:24:1)
    at Context.newResponse (file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/context.js:106:14)
    at Context.text (file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/context.js:124:45)
    at errorHandler (file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/hono-base.js:21:12)
    at file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/compose.js:58:33
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/hono-base.js:238:62 {
  code: 'ERR_INVALID_THIS'
}
    at Hono.errorHandler (file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/hono-base.js:19:11)
    at Hono.handleError (file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/hono-base.js:185:19)
    at file:///home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/hono/dist/hono-base.js:246:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server.<anonymous> (/home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/@hono/node-server/dist/server.js:48:20)
node:internal/url:527
      throw new ERR_INVALID_THIS('URLSearchParams');
            ^

TypeError [ERR_INVALID_THIS]: Value of "this" must be of type URLSearchParams
    at Proxy.getAll (node:internal/url:527:13)
    at Proxy.<anonymous> (/home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/@remix-run/web-fetch/dist/lib.node.cjs:1034:44)
    at Proxy.get (/home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/@remix-run/web-fetch/dist/lib.node.cjs:1067:23)
    at Server.<anonymous> (/home/miuzkle/project/hexo_blog/source/self/meting-api/node_modules/@hono/node-server/dist/server.js:53:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_THIS'
}

Node.js v20.11.1

**Comment by xizeyoupan** [comment]
node v20.11.1 (npm v10.2.4) 未能复现问题

**Comment by xizeyoupan** [comment]
633c102c839c6da20f1ea4862bb77034e3c53f01
