### ISSUE TITLE
打包运行表示该方法异常

### ISSUE THREAD

**Issue by EvanPengyou** [xizeyoupan/Meting-API#24]
[root@iZ2vcb2izu72doudn51a2vZ meeting-api]# deno run --allow-net --allow-env /www/server/meeting-api/deno.js
error: Uncaught (in promise) TypeError: that.write is not a function
  var actual = that.write(string, encoding);
                    ^
    at fromString2 (file:///www/server/meeting-api/deno.js:2136:21)
    at from2 (file:///www/server/meeting-api/deno.js:2096:12)
    at Function.Buffer3.from (file:///www/server/meeting-api/deno.js:2768:14)
    at file:///www/server/meeting-api/deno.js:35914:36
    at Array.forEach (<anonymous>)
    at node_modules/browserify-sign/browser/index.js (file:///www/server/meeting-api/deno.js:35913:29)
    at __require (file:///www/server/meeting-api/deno.js:11:50)
    at node_modules/crypto-browserify/index.js (file:///www/server/meeting-api/deno.js:42229:16)
    at __require (file:///www/server/meeting-api/deno.js:11:50)
    at file:///www/server/meeting-api/deno.js:44534:41

**Comment by xizeyoupan** [comment]
版本？Deno 1.43.1未能复现

**Comment by EvanPengyou** [comment]
![image](https://github.com/xizeyoupan/Meting-API/assets/88237124/e33807cb-ce36-4ece-9143-8e32f790b989)
版本也是1.43.1  可否分享一下已经打包好的js文件  有可能是我自己打包出来的文件问题

**Comment by xizeyoupan** [comment]
可以fork本项目然后运行下github action，可得到打包的文件

**Comment by EvanPengyou** [comment]
好的  谢谢
